### PR TITLE
Update references to py-rcsb_exdb_assets from development to master

### PR DESCRIPTION
**Pull request by brindakv**

### CODE REVIEW

**Comment by aliciaaevans** [comment]
This one just needs a header update comment.

**Comment by brindakv** [comment]
Thanks @aliciaaevans. I updated the header comment.

**Review by aliciaaevans — APPROVED** [review]

**Review by piehld — COMMENTED** [review]
LGTM too. Just one request—can I merge [my other PR](https://github.com/rcsb/py-rcsb_utils_targets/pull/7) into this PR?

**Comment by brindakv** [comment]
> Just one request—can I merge https://github.com/rcsb/py-rcsb_utils_targets/pull/7 into this PR?

Sure. There are no conflicts, I presume.

**Comment by piehld** [comment]
@brindakv Thanks, just merged my branch and updated the version and history. Please have a look and feel free to merge if it looks good. (No need to worry about mock-data here.)

**Pull request merged**
